name: inject
description: Inject annotation for `inject_generator` package library.
version: 1.0.0
repository: https://github.com/lamtx/inject

environment:
  sdk: ^2.19.0

dependencies:
  meta: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
